resolver: lts-16.31

packages:
- .

extra-deps:
  - blaze-colonnade-1.2.2.1
  - colonnade-1.2.0.2
  - Chart-diagrams-1.9.3
  - SVGFonts-1.7.0.1
  - diagrams-core-1.4.2
  - diagrams-lib-1.4.3
  - diagrams-postscript-1.5
  - diagrams-svg-1.4.3
  - svg-builder-0.1.1
  - active-0.2.0.14
  - dual-tree-0.2.2.1
  - monoid-extras-0.5.1
  - statestack-0.3
  - profunctors-5.4@sha256:f0cae8a572765e8fb6728c06f5482a1dc49cf36467a11f475f863000d2f6b486,2174
